### ISSUE TITLE
Use QT5

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/online_monitor#11]
Switch to Qt5

**Comment by DavidLP** [comment]
@leloup314 : Good practice is to run the unittest before comitting, to spot errors.
Just type `nosetests online_monitor`

**Comment by leloup314** [comment]
Thank you for fixing the Qt5 related imports. Nosetests now work but why are we testing [this](https://github.com/SiLab-Bonn/online_monitor/blob/development/online_monitor/testing/test_settings.py#L47-L48) ? It will always fail in nosetest if you changed the window size once, right?

**Comment by DavidLP** [comment]
Yes, as the message says it will fail if you rezise the monitor window. We are testing this because we want to be sure to have a minimum window size. Unittest CIs run on a fresh installations so they will not fail.

**Comment by leloup314** [comment]
Okay. There is no PyQt4 import anymore in online_monitor development (checked via: grep -rnw 'online_monitor/' -e 'PyQt4').

**Comment by DavidLP** [comment]
Seems t work. THX.
