### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by odnarod** [SiLab-Bonn/online_monitor#15]
At the moment, online_monitor is not compatible with py3 environments. Since many of the packages using online_monitor have moved to python 3, and regarding the end of support for py2, upgrading to python3 would be nice.

**Comment by DavidLP** [comment]
This package was always python 3 compatible and this is also [tested for](https://travis-ci.org/SiLab-Bonn/online_monitor/builds/400312969). Without an error description nothing can be done.

**Comment by YannickDieter** [comment]
In case of the [pytlu](https://github.com/SiLab-Bonn/pytlu) package (uses online monitor version 0.4.0) the build for python 2.7 is passing but not the build for python 3.7. See https://travis-ci.org/SiLab-Bonn/pytlu/builds/550242452?utm_source=github_status&utm_medium=notification

You can see the exact error description [here](https://travis-ci.org/SiLab-Bonn/pytlu/jobs/550242454#L3010).

**Comment by DavidLP** [comment]
Looks like that json changed its behaviour with strings between python 2 and 3. I will add unit tests to be able to spot changes in the underlying libraries.

**Comment by DavidLP** [comment]
And provide examples how to do serialization properly to ease use of this package.
