### ISSUE TITLE
Fixing order of receivers in Qt inferface

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/online_monitor#17]
The position of the tab widgets depend on the CPython version used. Testing fails in some cases where the test relies on
```PYTHON
self.online_monitor.tab_widget.setCurrentIndex(1)
```
as reported here: https://github.com/SiLab-Bonn/pymosa/pull/19

The reason is that different CPython versions are using different dict implementations: https://portingguide.readthedocs.io/en/latest/dicts.html

A possible fix overcomes the issue fix by enforcing alphabetical order (default in CPython 3.6 and higher).

**Comment by leloup314** [comment]
Is there a downside to using `OrderedDict` from `collections`? I use this quite frequently for exactly this reason. Asking just out of curiosity

**Comment by DavidLP** [comment]
No downside. Especially after the dict fix starting from [python 3.6](https://stackoverflow.com/questions/39980323/are-dictionaries-ordered-in-python-3-6), `OrderedDict` and `Dict` are actually the same implementation. After python 3.7 it is even a language feature. Honestly, we should just require python 3.6 and above. Everything else is nevertheless obsolete.

**Comment by DavidLP** [comment]
It is an interesting read though, how dict was improved. Fairly simple improvement and so important to do. Python is heavily relying on dicts.

**Comment by leloup314** [comment]
I actually followed this evolution of the `dict` a little bit. But I still mostly use `OrderedDict`, even with Python >=3.6, when I need to preserve the key order,  just for the sake of compatibility.

**Comment by laborleben** [comment]
So far I don't see any disadvantage of ```sorted()``` as far as the ```dict``` implementation remains the same in this respect.

**Comment by laborleben** [comment]
But the implementation details depends on the Python version used (CPython, PyPy, etc.). So ```sorted()``` is safe.

**Comment by laborleben** [comment]
But in the end you want to preserve the order of the yaml file (at least I think so). This could be more difficult as pointed out here: https://stackoverflow.com/questions/5121931/in-python-how-can-you-load-yaml-mappings-as-ordereddicts

**Comment by laborleben** [comment]
Having a predefined order could be done by using an additional parameter (e.g., tab_index) in the yaml file.

**Comment by DavidLP** [comment]
> But in the end you want to preserve the order of the yaml file (at least I think so).

Yea. That makes more sense.

> But the implementation details depends on the Python version used (CPython, PyPy, etc.).

For python 3.7 and above it is a language feature, thus irrelevant of implementation

**Comment by laborleben** [comment]
OK, I see. I leave that to someone else to fix/implement that. But luckily ```sorted()``` is not in contradiction to dict implementation in 3.7+.
