### ISSUE TITLE
Sometimes CRTL-C does not work

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/online_monitor#8]
Sometimes CRTL-C does not work. Some thread safe signal / slots are needed most likely.

**Comment by laborleben** [comment]
Interesting, Ctrl-C is handled and the abort parameter is set in main thread. So there should be no race condition. But I've never experienced this behavior.
Needing more details on the setup.

**Comment by leloup314** [comment]
Signals are used, guess this is more or less implemented already
