### ISSUE TITLE
High water mark does not work

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/online_monitor#9]
Actually this bug was never comitted, kept for reference.

The interface of pyZMQ for the HWM seems to be broken. The HWM under Linux via 
`zmq.setsockopt(zmq.SNDHWM / zmq.RCVHWM)`
does not work although plenty of examples show this.

The HWM is set correctly via:
`zmq.set_hwm()`

**Comment by themperek** [comment]
It may works just have to be set correctly.

**Comment by DavidLP** [comment]
But it was?

**Comment by DavidLP** [comment]
Fixed
